version: '3'

services:
  web:
    image: my-nginx-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./index.html:/var/www/html/index.html:ro
    restart: always

